In [1]:
import numpy as np
import pandas as pd
import xarray as xr

#### Create Xarray

In [2]:
# method 1

d1 = xr.DataArray(np.random.randint(5, size=(2, 3)),
                    dims=('x', 'y'),
                    coords={'x': [10, 20]})
#randint - changed from example to get integers
d1

# method 2
d2 = xr.DataArray(pd.Series(range(3), 
                       index=list('abc'), 
                       name='pd.DataFrame input'))
d2

<xarray.DataArray 'pd.DataFrame input' (dim_0: 3)>
array([0, 1, 2])
Coordinates:
  * dim_0    (dim_0) object 'a' 'b' 'c'

#### Key properties

In [3]:
d1.values # values in the np rand
d1.dims # set dimentions 
d1.coords # set cooords

d2.values # values in pd.Series
d2.dims # 1 by
d2.coords # indexes all labels in the dim_0


Coordinates:
  * dim_0    (dim_0) object 'a' 'b' 'c'

#### Indexing 
###### (number 4 is ideal/easy/lazy for Xarray

In [4]:
# positional and by integer label (i.e numpy)
print('idx #1:\n', d1[[0,1]])

#positional and by coordinate label (i.e pandas)
print('idx #2:\n', d1.loc[10:20]) #recall, the x dim labels assigned

# by dimension name and integer label
print('idx #3:\n', d1.isel(x=slice(2)))

# by dimension name and coordinate label
print('idx #4:\n', d1.sel(x=[10,20]))


idx #1:
 <xarray.DataArray (x: 2, y: 3)>
array([[0, 0, 4],
       [2, 4, 3]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y
idx #2:
 <xarray.DataArray (x: 2, y: 3)>
array([[0, 0, 4],
       [2, 4, 3]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y
idx #3:
 <xarray.DataArray (x: 2, y: 3)>
array([[0, 0, 4],
       [2, 4, 3]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y
idx #4:
 <xarray.DataArray (x: 2, y: 3)>
array([[0, 0, 4],
       [2, 4, 3]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y


#### Attributes
###### Xarray will label plots with this info if you supply it (one and done!)

In [ ]:
# OrderedDict stored as attributes in Xarray
d1.attrs['long_name'] = 'give_it_a_long_descriptive_name'
d1.attrs['units'] = 'meters'
d1.attrs['description'] = 'A random variable created as an example.'
d1.attrs['random_attribute'] = 123

#add to coordinates too
d1.x.attrs['units'] = 'x units'
d1.attrs

#### Computation
###### very similar to numpy ndarrays

In [ ]:
d1+10

#m to cm
d1*100